# Generated by Django 5.2.17 on 2026-09-16 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('desired_skills', models.JSONField(blank=True, default=list)),
                ('education_level', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('CLOSED', 'Cerrada'), ('DRAFT', 'Borrador')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
