# Generated by Django 5.2.17 on 2026-09-16 06:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=100)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('education', models.CharField(blank=True, default='', max_length=200)),
                ('performance_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_high_performer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-performance_score'],
            },
        ),
    ]
