# Generated by Django 5.2.17 on 2026-09-19 20:31

import apps.candidates.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En evaluación'), ('EVALUATED', 'Evaluado'), ('RECOMMENDED', 'Recomendado'), ('NOT_RECOMMENDED', 'No recomendado')], default='PENDING', max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('extracted_profile', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=apps.candidates.models.cv_upload_path)),
                ('cv_file_name', models.CharField(blank=True, max_length=255)),
                ('cv_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('cv_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='jobs.job')),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
